### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by nlzet** [dsentker/phpinsights#1]
Hi,

I am using this in a project, is it possible to create a first tag, so we don't need to require dev-master ? Could be a 0.x tag.

**Comment by barryvdh** [comment]
So is tagged, but you need to update your Packagist webhook so tags are updated too :)
(You can update manually if you need to also, but not very practical)

**Comment by dsentker** [comment]
Yes, i need more practice in that. I think it should be synced now.
